---

name: Continuous Integration

on: [push]

jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Installing node
        uses: actions/setup-node@v2
      - name: Install Node Modules
        run: |
          npm ci
      - name: Running test
        run: |
          npm run test

  linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
